spring.application.name=SaraswatiHoribollCommittee


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/durgapuja


spring.datasource.username=root
spring.datasource.password=Password#1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cloudinary.cloud_name=dbryfllm2
cloudinary.api_key=712284175582917
cloudinary.api_secret=EeZlRCDye0B3wjj6dKB8Xu4OctU
