spring.application.name=SaraswatiHoribollCommittee


server.port=8081

spring.datasource.url=jdbc:mysql://mysql-157d9186-sayondeep1618-e157.j.aivencloud.com:19333/defaultdb?sslMode=REQUIRED


spring.datasource.username=avnadmin
spring.datasource.password=AVNS_bfq-BdnrJrovtNjPEpX
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cloudinary.cloud_name=dbryfllm2
cloudinary.api_key=712284175582917
cloudinary.api_secret=EeZlRCDye0B3wjj6dKB8Xu4OctU

razorpay.key.id=rzp_test_SnlXRoZ9cEQ84q
razorpay.key.secret=XJ3E3wgy2SFA8qfFBzhlBauI
